# Generated by Django 2.1.2 on 2018-12-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnasayfaBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('site', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
