# Generated by Django 2.1.2 on 2018-12-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bs4cron', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnasayfaBlog',
        ),
    ]
