# Generated by Django 2.1 on 2018-12-08 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('site', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('searchtimeblog', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=250, null=True)),
                ('track', models.DecimalField(decimal_places=2, max_digits=6)),
                ('crontime', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=550, null=True)),
                ('image', models.CharField(max_length=550, null=True)),
                ('user', models.CharField(max_length=250, null=True)),
                ('no', models.IntegerField()),
                ('site', models.CharField(max_length=250, null=True)),
                ('pricedisplay', models.CharField(max_length=250, null=True)),
                ('serinotrack', models.CharField(default='234', max_length=250, null=True)),
                ('email', models.CharField(default='tugrulv89@gmail.com', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('pricedisplay', models.CharField(max_length=250, null=True)),
                ('keyword', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('site', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('searchtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageurl', models.CharField(max_length=450)),
                ('serino', models.CharField(max_length=150)),
                ('email', models.CharField(default='tugrulv89@gmail.com', max_length=250, null=True)),
            ],
        ),
    ]
