# Generated by Django 2.1.2 on 2018-12-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopist', '0003_anasayfablog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnasayfaBlog',
            new_name='Blogs',
        ),
    ]
